# Generated by Django 2.0.5 on 2018-05-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
