# Generated by Django 2.0.5 on 2018-05-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0003_auto_20180530_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_active',
            new_name='contributor',
        ),
    ]
