# Generated by Django 2.0.5 on 2018-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0004_auto_20180531_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contributor',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is it active?'),
        ),
    ]
