# Generated by Django 2.0.5 on 2018-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0005_auto_20180531_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contributor',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Desejo contribuir com o valor de R$ 5,00'),
        ),
    ]
