# Generated by Django 2.0.5 on 2018-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0008_auto_20180531_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(choices=[('groups', 'Fase de grupos'), ('16', 'Oitavas de final'), ('8', 'Quartas de final'), ('4', 'Semi-final'), ('2', 'Final')], default='groups', max_length=100),
        ),
    ]
