# Generated by Django 2.0.5 on 2018-06-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0010_auto_20180605_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotsite.Group'),
        ),
    ]
