# Generated by Django 2.0.5 on 2018-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotsite', '0012_auto_20180605_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contributor',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Desejo contribuir com o valor de R$ 5,00'),
        ),
    ]
